apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: {{ .Release.Name }}-api
          image: {{ .Values.api.registry }}:{{ .Values.api.version }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 80Mi
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: VERSION_TAG
              value: {{ .Values.api.version }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-api-config-map
      imagePullSecrets:
        - name: {{ .Values.api.registrySecretName }}
