apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: {{ .Values.api.port }}
      name: http
      targetPort: 9000
