apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtual-service
spec:
  hosts:
  - {{ required "A valid value for api.host must be provided" .Values.api.host | quote }}
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ required "A valid value for api.port must be provided" .Values.api.port }}
        host: {{ .Release.Name }}-svc
