gateway:
  tls: false
  apiHost: api.local.stingyvegan.com
  clientHost: local.stingyvegan.com
  rabbitmqHost: rabbit.local.stingyvegan.com

sv-api:
  postgres:
    include: true
  rabbitmq:
    include: false
    host: stingyvegan-rabbitmq
  gateway:
    include: false
    name: stingyvegan-gateway

sv-client:
  gateway:
    include: false
    name: stingyvegan-gateway

rabbitmq:
  include: true
  auth:
    username: sv
    password: sv
